name = "Panel and hvPlot"
description = "Leverage hvPlot interactive feature and extending it with Panel."
packages = ["geopandas", "matplotlib.pyplot", "shapely.geometry", "urllib.request", "bs4", "re", "ast", "requests", "PIL", "numpy", "io", "datetime"]
